services:
  pg:
    image: postgres:15.6
    restart: always
    container_name: pg
    env_file:
      - ./.env
    volumes:
      - pg-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

#  api:
#    build: .
#    container_name: assessment-api
#    env_file:
#      - ./.env
#    depends_on:
#      pg:
#        condition: service_healthy
#    ports:
#      - ${PORT}:${PORT}
#    environment:
#      NODE_ENV: ${NODE_ENV}
#      PORT: ${PORT}
#      DB_USERNAME: ${DB_PASSWORD}
#      DB_PASSWORD: ${DB_USERNAME}
#      DB_HOST: ${DB_HOST}
#      DB_PORT: ${DB_PORT}
#      DB_DATABASE: ${DB_DATABASE}
#      PRIV_KEY_PATH: ${PRIV_KEY_PATH}
#      PUB_KEY_PATH: ${PUB_KEY_PATH}
#      UI_URL: ${UI_URL}

volumes:
  pg-db-data:
