name: test & build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Env
        run: |
          openssl genrsa -out keys/private.key 2048
          openssl rsa -in keys/private.key -pubout -out keys/public.key
          touch .env
          echo NODE_ENV=pipeline >> .env
          echo UI_URL=* >> .env
          echo PORT=4000 >> .env
          echo DB_HOST=localhost >> .env
          echo DB_USERNAME=assessment >> .env
          echo DB_PASSWORD=assessment >> .env
          echo DB_DATABASE=assessment_db >> .env
          echo DB_PORT=5432 >> .env
          echo "PUB_KEY_PATH=\"./keys/public.key\"" >> .env
          echo "PRIV_KEY_PATH=\"./keys/private.key\"" >> .env

      - name: Compose up
        run: docker compose up -d

      - name: NPM install
        run: npm install

      - name: Prettier format
        run: npx prettier . --check

      - name: Db migrations
        run: bash migrate.sh

      - name: Test
        run: npm run test

      - name: Build Dockerfile
        run: docker build -t iTchTheRightSpot/learnly-assessment .

      - name: Compose down
        run: docker compose down -v
